# @package dataset
# cfg:
  # torch data-loader specific arguments
cfg: 
  batch_size: ${training.batch_size}
  num_workers: ${training.num_workers}
  dataroot: data

  common_transform: None
  aug_transform: None
  pre_transform: None

  val_transform: "${dataset.cfg.common_transform}"
  test_transform: "${dataset.cfg.val_transform}"
  train_transform: 
    - "${dataset.cfg.aug_transform}"
    - "${dataset.cfg.common_transform}"