defaults:
  - task: ???
  - models: ???
  - data: ???
  - training: default
  - trainer: default

job_name: benchmark
model_name: ???
update_lr_scheduler_on: "on_epoch" # ["on_epoch", "on_num_batch", "on_num_sample"]
selection_stage: ""
pretty_print: False
eval_frequency: 1

tracker_options:
  # Extra options for the tracker
  full_res: False
  make_submission: False
  track_boxes: False
